version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: quickbite_backend

    command: >
      sh -c "python manage.py migrate --noinput &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: quickbite_frontend

    command: npm run dev -- --host 0.0.0.0

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

    depends_on:
      - backend

    restart: unless-stopped

  postgres:
    image: postgres:17-alpine

    container_name: quickbite_postgres

    environment:
      POSTGRES_DB: food_ordering_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: quickbite_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: