# Generated by Django 5.2.15 on 2026-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
